drama:
  - "Alblaka removes compatibility between Too Many Items and BuildCraft by request of Direwolf20"
  - "SpaceToad plays OpenPeripheral on Twitch"
  - "MachineMuse confirms that OpenBlocks should be less like Chisel"
  - "kirindave threatens to complain about Shukaro until they remove Natura from Resonant Rise"
  - "nallar adds compatibility between ExtraBiomesXL and VoxelMap by request of kakermix"
  - "Sengir denies OpenPeripheral is faster than RedPower 3"
  - "MamiyaOtaru steals code from Highlands"
  - "Alblaka decides to base their entire modpack on Pixelmon"
  - "Vswe says PowerCrystals did not steal 5 lines of code from RealSketch"
  - "RWTema tweets tgame14 stole 5 lines of code from Reika"
  - "Player complains that MamiyaOtaru replaced Forge MultiPart by RedPower 3"
  - "Notch quits the development team of Extra Cells"
  - "BevoLJ complains about LexManos's surprisingly small profit from Flattr"
  - "Vazkii complains about Ex Aliquo breaking magic"
  - "Extra Cells adds code to ban people playing with Thermal Expansion 3"
  - "Admins of survival servers think KingLemming's actions are wonderful"
  - "Grum adds RedPower 3 to ForgeCraft"
  - "Greymerk tweets ForgeCraft causes drama when used with Wireless Redstone"
  - "IRC urges everyone to stop enjoying Mo' Creatures"
  - "Shadowclaimer finds adware in Natura"
  - "pixlepix rants about Carpenter's Blocks on Twitch"
  - "Fans of Equivalent Exchange and Agriculture argue on GregTech thread"
  - "JAKJ and Soaryn came out against imbalance, the Mojang blog rages"
  - "Velotican quits the development team of IndustrialCraft 2"
  - "CovertJaguar threatens to kick jadedcat until they remove GregTech from CurseForge"
  - "Hunterz says closed-source mods is less buggy than Pixelmon"
